language: python node_js
python:
    - "3.5"
node_js:
    - "node"
before_install:
    - sudo apt-get update -y
    - sudo apt-get install -y
        curl
        npm
    - wget https://github.com/spf13/hugo/releases/download/v0.17/hugo_0.17-64bit.deb
    - sudo dpkg -i hugo_0.17-64bit.deb
install:
    - pip3 install -r requirements.txt
script: /bin/bash deploy.sh
