language: python node_js
python:
    - "3.5"
node_js:
    - "node"
before_install:
    - sudo apt-get update -y
    - sudo apt-get install -y
        curl
        npm
    - wget https://github.com/spf13/hugo/releases/download/v0.17/hugo_0.17-64bit.deb
    - sudo dpkg -i hugo_0.17-64bit.deb
    - openssl aes-256-cbc -K $encrypted_56a395b73f83_key -iv $encrypted_56a395b73f83_iv -in travisci_rsa.enc -out travisci_rsa -d
    - chmod 600 travisci_rsa
    - eval `ssh-agent -s`
    - ssh-add travisci_rsa
    - rm travisci_rsa
    - git config user.name "Travis CI"
    - git config user.email "$(COMMIT_AUTHOR_EMAIL)"
    - git config push.default tracking
    - GITHUB_REPO_URL=`git remote -v | grep -m1 '^origin' | sed -Ene's#.*(https://[^[:space:]]*).*#\1#p'`
    - GITHUB_USER=`echo $GITHUB_REPO_URL | sed -Ene's#https://github.com/([^/]*)/(.*).git#\1#p'`
    - GITHUB_REPO=`echo $GITHUB_REPO_URL | sed -Ene's#https://github.com/([^/]*)/(.*).git#\2#p'`
    - GITHUB_REPO_SSH_URL="git@github.com:$(GITHUB_USER)/$(GITHUB_REPO).git"
    - git remote set-url origin $GITHUB_REPO_SSH_URL
install:
    - pip3 install -r requirements.txt
script: make travis
