baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "en-us"
title = "SalmoNet"
theme = "SalmoNet"
Paginate = 10
disqusShortname = "xxxx"

[params]
  description = "Demo site for a hugo theme"
  google_analytics = "UA-xxxxxx-xx"