baseurl = "https://korcsmarosgroup.github.io/SalmoNet2/"
languageCode = "en-us"
title = "SalmoNet"
theme = "SalmoNet"
Paginate = 10

[params]
  description = "Demo site for a hugo theme"
  google_analytics = "UA-73347324-4"
